# Generated by Django 5.2.6 on 2025-09-12 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('recorrencia_tipo', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='nenhuma', max_length=10)),
                ('recorrencia_dia_semana', models.IntegerField(blank=True, null=True)),
                ('recorrencia_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('lider', 'Líder'), ('membro', 'Membro')], default='membro', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='app.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='lider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_lider', to='app.pessoa'),
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='app.pessoa')),
            ],
            options={
                'unique_together': {('pessoa', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data', models.DateField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='app.evento')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='app.funcao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='app.pessoa')),
            ],
            options={
                'unique_together': {('evento', 'pessoa', 'funcao', 'data')},
            },
        ),
        migrations.CreateModel(
            name='PessoaFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_funcao', to='app.funcao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_pessoa', to='app.pessoa')),
            ],
            options={
                'unique_together': {('pessoa', 'funcao')},
            },
        ),
    ]
