# Generated by Django 5.2.7 on 2025-10-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('evento', 'pessoa', 'funcao')},
        ),
        migrations.RemoveField(
            model_name='escala',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='data',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='mes',
        ),
    ]
